# Generated by Django 5.1 on 2024-10-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('acoustic', models.FloatField()),
                ('dance', models.FloatField()),
                ('duration', models.IntegerField()),
                ('energy', models.FloatField()),
                ('instrumental', models.FloatField()),
                ('key', models.IntegerField()),
                ('liveness', models.FloatField()),
                ('loud', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speech', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('dating_profile', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
