# Generated by Django 5.1 on 2024-11-01 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('acoustic', models.FloatField()),
                ('dance', models.FloatField()),
                ('duration', models.IntegerField()),
                ('energy', models.FloatField()),
                ('instrumental', models.FloatField()),
                ('key', models.IntegerField()),
                ('liveness', models.FloatField()),
                ('loud', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speech', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('popularity', models.FloatField(null=True)),
                ('dating_profile', models.JSONField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('preview', models.URLField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDislikedSongs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('disliked_songs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikedSongs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('liked_songs', models.JSONField(default=list)),
            ],
        ),
    ]
