# Generated by Django 5.1 on 2024-11-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikedsongs',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDislikedSongs',
        ),
        migrations.DeleteModel(
            name='UserLikedSongs',
        ),
    ]
