# Generated by Django 5.1 on 2024-10-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
