# Generated by Django 5.1 on 2024-10-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_image_song_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
