# Generated by Django 5.1 on 2024-11-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_userlikedsongs_user_delete_userdislikedsongs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('centroid', models.JSONField()),
                ('cluster_type', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked')], max_length=10)),
            ],
        ),
    ]
