# Generated by Django 5.1 on 2024-11-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='cluster_type',
        ),
        migrations.AddField(
            model_name='cluster',
            name='genre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
