# Generated by Django 5.1 on 2024-10-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='popularirty',
            field=models.FloatField(null=True),
        ),
    ]
