# Generated by Django 5.1 on 2024-10-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_popularirty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='popularirty',
            new_name='popularty',
        ),
    ]
