# Generated by Django 5.1 on 2024-10-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_popularirty_song_popularty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='popularty',
            new_name='popularity',
        ),
    ]
