# Generated by Django 5.1 on 2024-10-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_popularty_song_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
