# Generated by Django 5.1 on 2024-11-01 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('music', '0012_remove_cluster_user_remove_clustermetadata_cluster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikedSongs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('liked_songs', models.ManyToManyField(blank=True, to='music.song')),
            ],
        ),
    ]
