# Generated by Django 5.1 on 2024-11-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_userlikedsongs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSongPreference',
        ),
    ]
