# Generated by Django 5.1 on 2024-11-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_delete_usersongpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikedsongs',
            name='liked_songs',
        ),
        migrations.AddField(
            model_name='userlikedsongs',
            name='liked_songs',
            field=models.JSONField(default=list),
        ),
    ]
