# Generated by Django 5.1 on 2024-11-01 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('music', '0015_remove_userlikedsongs_liked_songs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDislikedSongs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('disliked_songs', models.JSONField(default=list)),
            ],
        ),
    ]
