# Generated by Django 5.1 on 2024-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_user_username'),
        ('music', '0002_remove_userlikedsongs_user_delete_userdislikedsongs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_songs',
            field=models.ManyToManyField(blank=True, related_name='disliked_by_users', to='music.song'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='music.song'),
        ),
    ]
