# Generated by Django 5.1 on 2024-11-01 19:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_user_disliked_songs_user_liked_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_song_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_song_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked_cluster', models.BooleanField()),
                ('centroid', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
