# Generated by Django 5.1 on 2024-11-01 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_user_disliked_song_count_user_liked_song_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercluster',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='usercluster',
            name='is_liked_cluster',
        ),
        migrations.RemoveField(
            model_name='usercluster',
            name='radius',
        ),
        migrations.AddField(
            model_name='usercluster',
            name='disliked_clusters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='usercluster',
            name='liked_clusters',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='usercluster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_clusters', to=settings.AUTH_USER_MODEL),
        ),
    ]
