# Generated by Django 5.1 on 2024-11-01 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_remove_usercluster_centroid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercluster',
            name='disliked_clusters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercluster',
            name='liked_clusters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercluster',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cluster', to=settings.AUTH_USER_MODEL),
        ),
    ]
