# music/services/generative_ai_service.py

import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold
import random
from .musixmatch_service import get_lyrics
import os

CATEGORIES = [
    "boring",
    "fun",
    "sassy",
    "straight forward",
    "joke",
    "not looking for anything serious",
    "adventurous",
    "romantic",
    "intellectual",
    "mysterious",
    "depressed",
    "anxious",
    "outgoing",
    "introverted",
    "shy",
    "pretentious",
    "indie",
    "laid-back",
    "flirty",
    "ambitious",
    "spontaneous",
    "creative",
    "humorous",
    "caring",
    "traditional",
    "quirky",
    "super weird",
    "genius",
    "put a joke in this bio",
    'super short bio, like less than a sentence',
    "maybe a psychopath?",
    "probably on the internet a bit too much",
    "thinks they are better than everyone",
    "uses too many big words",
    "thinks they are the main character",
    "obviously generated by a llm",
    "all they care about is their dog or cat",
    "has big dreams",
    "definitely a virgin",
    "already thinking about marriage",
    "probably underaged...",
    "I downloaded the app as a joke",
    "don't text me, I'm never on this app",
    "Still a student",
    "Definitely only looking for someone to give them free stuff aka Gold Digger",
    "definitely a republican",
    "definitely a democrat",
    "strong political views",
    "might be a racist...",
    "did not go to college",
    "lots of spelling and grammatical errors, but make it realistic for what a human can do",
    "misogynist",
    "Hates men, absolutely hates men",
    "definitely unemployed",
    "only here for a hookup",
    "tourist and not from the area",
    "trust fund baby"
]

def parse_dating_profile(dating_profile_text):
    lines = dating_profile_text.strip().split("\n")
    profile_data = {
        "gender": lines[0] if len(lines) > 0 else "N/A",
        "sexuality": lines[1] if len(lines) > 1 else "N/A",
        "height": lines[2] if len(lines) > 2 else "N/A",
        "biography": lines[3] if len(lines) > 3 else "N/A",
        "interest_list": lines[4] if len(lines) > 4 else "N/A",
        "age": lines[5] if len(lines) > 5 else "N/A",
        "occupation": lines[6] if len(lines) > 6 else "N/A",
        "location": lines[7] if len(lines) > 7 else "N/A",
    }
    return profile_data

def get_dating_profile(song_name, artist_name, stats):
    """
    Generates a dating profile based on song information using Google Generative AI.
    """
    genai.configure(api_key=os.getenv("GENAI_API_KEY"))  # Move API key to .env

    # Create the model
    generation_config = {
        "temperature": 1,
        "top_p": 0.95,
        "top_k": 64,
        "max_output_tokens": 8192,
        "response_mime_type": "text/plain",
    }

    model = genai.GenerativeModel(
        model_name="gemini-1.5-flash",
        generation_config=generation_config,
        safety_settings={
            HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
        }
    )

    chat_session = model.start_chat(history=[])
    cats = random.sample(CATEGORIES, 3)
    print(cats)

    base_message = (
        f"You are creating a dating app profile for songs, I will provide you some of their lyrics, song name, and artist name, "
        f"as well as some of their metrics such as acoustic (A confidence measure from 0.0 to 1.0 of whether the track is acoustic. "
        f"1.0 represents high confidence the track is acoustic.), dance (Danceability describes how suitable a track is for dancing based on a combination "
        f"of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.), "
        f"duration (The duration of the track in milliseconds.), energy (Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity "
        f"and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. "
        f"Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.), "
        f"instrumental (Predicts whether a track contains no vocals. \"Ooh\" and \"aah\" sounds are treated as instrumental in this context. Rap or spoken word tracks are "
        f"clearly \"vocal\". The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended "
        f"to represent instrumental tracks, but confidence is higher as the value approaches 1.0.), key (The key the track is in. Integers map to pitches using standard Pitch "
        f"Class notation. E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1), liveness (Detects the presence of an audience in the recording. "
        f"Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live), "
        f"loud (The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. "
        f"Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db.), "
        f"mode (Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0.), "
        f"speech (Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. "
        f"Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, "
        f"either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.), tempo (The overall estimated tempo of a track in beats per minute (BPM). "
        f"In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.), and valence (A measure from 0.0 to 1.0 describing the musical positiveness "
        f"conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).) "
        f"The overarching theme of the profile will be {cats[0]}, {cats[1]}, and {cats[2]}"
    )
    
    explanation = (
        "Use these metrics to generate a gender, sexuality, height, biography, interest list, age, occupation, and location. "
        "Do not explain the reasonings, just give a response. Interest list should be one word or two word interests, and try to aim for 4 different interests but have them be a comma separated list. "
        "This can be various sports, types of music, photography, just any general hobby, since they are all song related, try to not use music or dancing or make them more specific, biography should be limited to 2 sentences. "
        "For each category, separate them by a newline. Try to be creative with the bio and thematic with the provided themes. Additionally, do not talk about yourself as a song, you are a person, not a song."
    )
    
    lyrics = get_lyrics(artist_name, song_name)
    
    real_message = (
        f"{base_message} {explanation} The lyrics are: {lyrics}, the song name is {song_name}, artist name is {artist_name}, "
        f"acoustic {stats[0]}, dance {stats[1]}, duration {stats[2]}, energy {stats[3]}, instrumental {stats[4]}, key {stats[5]}, "
        f"liveness {stats[6]}, loud {stats[7]}, mode {stats[8]}, speech {stats[9]}, tempo {stats[10]}, valence {stats[11]}"
    )
    
    response = chat_session.send_message(real_message)
    return response.text
